// Hate to have to put it here but oh well.

#define NCASE "ncase"
#define GCASE "gcase"
#define DCASE "dcase"
#define ACASE "acase"
#define ICASE "icase"
#define PCASE "pcase"
#define RUGENDER "rugender"
#define PLURAL_NCASE "plural_ncase"
#define PLURAL_GCASE "plural_gcase"
#define PLURAL_DCASE "plural_dcase"
#define PLURAL_ACASE "plural_acase"
#define PLURAL_ICASE "plural_icase"
#define PLURAL_PCASE "plural_pcase"
#define PLURAL_RUGENDER "plural_rugender"
